version: '3.8'
services:
  db:
    container_name: postgres
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_USER: root
      POSTGRES_DB: tododb
    volumes:
      - ./database/dbcontainer:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  app:
    container_name: flask
    build:
      context: .
      dockerfile: Dockerfile
    # command: python app.py
    # command: gunicorn -b :5000 main:app
    # command: flask --app main.py run --host 0.0.0.0 --port 5000 --reload
    command: gunicorn -b 0.0.0.0:5000 -c gunicorn.conf.py main:app --reload
    volumes:
      - '.:/app'
    ports:
      - "5000:5000"
    depends_on:
      - db